const inputData = {
    text: {
        label: 'text-input',
        defaultValue: '',
        template: 'Input',
        module: {
            label: 'text-input',
            defaultValue: '',
            template: 'Input',
        },
        name: 'label',
        isSidebar: true,
        hasError: false,
        enabled: true,
        errors: [],
    },
    number: {
        inputType: 'Number',
        template: 'Input',
        label: 'number-input',
        module: {
            defaultValue: '5000',
            inputType: 'Number',
            template: 'Input',
            label: 'number-input',
        },
        data: {
            id: 'uw845x42',
            value: '73',
            title: '30k',
            count: '30000',
            speed: '500',
            dynamicCountUp: true,
            content: 'Hello, here is the content of circle item',
        },
        name: 'count',
        isSidebar: true,
        hasError: false,
        enabled: true,
        errors: [],
    },
    input: {
        template: 'Input',
        label: 'input-input',
        activeHover: false,
        module: {
            template: 'Input',
            label: 'input-input',
        },
        name: 'customForm/field/requiredText/text',
        isSidebar: true,
        hasError: false,
        enabled: true,
        errors: [],
    },
    textarea: {
        template: 'Input',
        inputType: 'textarea',
        label: 'textarea-input',
        addOptions: true,
        cmsFields: ['!IMAGE', '!LIST', '!RICH_TEXT'],
        activeHover: false,
        module: {
            template: 'Input',
            inputType: 'textarea',
            label: 'textarea-input',
            addOptions: true,
            cmsFields: ['!IMAGE', '!LIST', '!RICH_TEXT'],
        },
        name: 'settings/meta/description',
        isSidebar: true,
        hasError: false,
        enabled: true,
        errors: [],
    },
    time: {
        label: 'time-input',
        template: 'Input',
        inputType: 'time',
        activeHover: false,
        module: {
            label: 'time-input',
            template: 'Input',
            inputType: 'time',
        },
        data: {
            type: 'counterdown',
            name: 'Countdown Timer',
            _elType: 'ELEMENT',
            component_path: 'counterdown',
            counter: {
                text: {
                    days: 'Days',
                    hours: 'Hours',
                    minutes: 'Minutes',
                    seconds: 'Seconds',
                },
                date: '2023-09-19',
                GMT: '+00:00',
                finishText: 'The countdown is over!',
                align: 'left',
            },
            id: 'smel6biy',
        },
        name: 'counter/time',
        isSidebar: true,
        hasError: false,
        enabled: true,
        errors: [],
    },
    date: {
        label: 'date-input',
        template: 'Input',
        inputType: 'date',
        activeHover: false,
        module: {
            label: 'date-input',
            template: 'Input',
            inputType: 'date',
        },
        data: {
            type: 'counterdown',
            name: 'Countdown Timer',
            _elType: 'ELEMENT',
            component_path: 'counterdown',
            counter: {
                time: '00:02:04',
                GMT: '+00:00',
                finishText: 'The countdown is over!',
                align: 'left',
            },
            id: 'smel6biy',
        },
        name: 'counter/date',
        value: '2023-09-10',
        isSidebar: true,
        hasError: false,
        enabled: true,
        errors: [],
    },
    id: {
        prefix: '#',
        label: 'id-input',
        template: 'InputID',
        module: {
            prefix: '#',
            label: 'id-input',
            template: 'InputID',
        },
        data: {
            id: 'ri84d7gh',
            type: 'radio',
            label: 'Radio Input',
            name: 'Radio Input',
            options: ['asdfasdf', 'asdfasdfa', 'asdfasdfb', 'asdfasdfc'],
            htmlAttributes: [],
            htmlId: 'asdf-asdf',
        },
        name: 'htmlId',
        isSidebar: true,
        hasError: false,
        enabled: true,
        errors: [],
    },
    url: {
        label: 'url-input',
        template: 'InputUrl',
        placeholder: 'http://example.com',
        info: 'URL should start with http:// or https://',
        module: {
            label: 'url-input',
            template: 'InputUrl',
            placeholder: 'http://example.com',
            info: 'URL should start with http:// or https://',
        },
        data: {
            id: '2suuvmpu',
            label: 'Link 1',
        },
        name: 'url',
        validate:
            /[(http(s)?)://(www.)?a-zA-Z0-9@:%._+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_+.~#?&//=]*)/,
        isSidebar: true,
        hasError: false,
        enabled: true,
        errors: [],
    },
};
const prependInput = {
    label: 'prepend-label',
    template: 'PrependInput',
    prefix: 'mailto:',
    cmsFields: ['!IMAGE', '!LIST', '!RICH_TEXT'],
    activeHover: false,
    module: {
        label: 'prepend-label',
        template: 'PrependInput',
        prefix: 'mailto:',
        cmsFields: ['!IMAGE', '!LIST', '!RICH_TEXT'],
    },
    name: 'wrapper/attr/href',
    value: 'asdf@email.com',
    isSidebar: true,
    hasError: false,
    enabled: true,
    errors: [],
};

export { inputData, prependInput };
