const defaultFont = [
    {
        label: 'Arial',
        fallbackTo: 'sans-serif',
        weight: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
            '800',
            '900',
            'bold',
            'lighter',
            'normal',
            'bolder',
        ],
    },
    {
        label: 'Arial Black',
        fallbackTo: 'sans-serif',
        weight: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
            '800',
            '900',
            'bold',
            'lighter',
            'normal',
            'bolder',
        ],
    },
    {
        label: 'Tahoma',
        fallbackTo: 'sans-serif',
        weight: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
            '800',
            '900',
            'bold',
            'lighter',
            'normal',
            'bolder',
        ],
    },
    {
        label: 'Verdana',
        fallbackTo: 'sans-serif',
        weight: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
            '800',
            '900',
            'bold',
            'lighter',
            'normal',
            'bolder',
        ],
    },
    {
        label: 'Trebuchet MS',
        fallbackTo: 'sans-serif',
        weight: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
            '800',
            '900',
            'bold',
            'lighter',
            'normal',
            'bolder',
        ],
    },
    {
        label: 'Georgia',
        fallbackTo: 'serif',
        weight: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
            '800',
            '900',
            'bold',
            'lighter',
            'normal',
            'bolder',
        ],
    },
    {
        label: 'Palantino',
        fallbackTo: 'serif',
        weight: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
            '800',
            '900',
            'bold',
            'lighter',
            'normal',
            'bolder',
        ],
    },
    {
        label: 'Times New Roman',
        fallbackTo: 'serif',
        weight: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
            '800',
            '900',
            'bold',
            'lighter',
            'normal',
            'bolder',
        ],
    },
    {
        label: 'Palantino',
        fallbackTo: 'serif',
        weight: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
            '800',
            '900',
            'bold',
            'lighter',
            'normal',
            'bolder',
        ],
    },
    {
        label: 'Courier New',
        fallbackTo: 'monospace',
        weight: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
            '800',
            '900',
            'bold',
            'lighter',
            'normal',
            'bolder',
        ],
    },
];

export default defaultFont;
