import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faGift as fasGift,
    faCog,
    faColumns,
    faPlusCircle,
    faGripVertical,
    faCogs,
    faPaintBrush,
    faChevronDown,
    faChevronUp,
    faChevronRight,
    faDesktop,
    faTabletAlt,
    faMobileAlt,
    faDesktopAlt,
    faFillDrip,
    faAdjust,
    faImage,
    faVideo,
    faMagic,
    faInfoCircle,
    faCheck,
    faTrashAlt,
    faEllipsisV,
    faEllipsisH,
    faBan,
    faTimes,
    faHome as fasHome,
    faDoNotEnter as fasDoNotEnter,
    faCheckCircle as fasCheckCircle,
    faTimesCircle as fasTimesCircle,
    faExclamationCircle as fasExclamationCircle,
} from '@fortawesome/pro-solid-svg-icons';
import {
    faHdd,
    faEdit,
    faSave,
    faPlus,
    faBars,
    faPlug,
    faLink,
    faClock,
    faTools,
    faClone,
    faTrash,
    faBooks,
    faMinus,
    faEraser,
    faUnlink,
    faUpload,
    faLockAlt,
    faSyncAlt,
    faSignOut,
    faEnvelope,
    faExchange,
    faAlignLeft,
    faLayerPlus,
    faAlignRight,
    faAlignCenter,
    faAlignJustify,
    faArrowsAlt,
    faBorderAll,
    faUserCircle,
    faTable,
    faFileExport,
    faFileImport,
    faPaperPlane,
    faLayerGroup,
    faLaptopCode,
    faEyeDropper,
    faUserHeadset,
    faAngleLeft,
    faSparkles,

    // faClock as fadClock,
    faEye as faEyeR,
    faCog as faCogR,
    faClipboardList,
    faLongArrowLeft,
    faLongArrowRight,
    faFile as farFile,
    faCogs as farCogs,
    faHome as farHome,
    faPencilPaintbrush,
    faGlobe as farGlobe,
    faSpinner as faSpinnerR,
    faSearch as farSearch,
    faTrashAlt as faTrashAltR,
    faUserSlash as farUserSlash,
    faEllipsisV as faEllipsisVR,
    faUserShield as farUserShield,
    faChevronRight as faChevronRightR,
    faChevronUp as farChevronUp,
    faChevronDown as farChevronDown,
    faColumns as farColumns,
    faFolderTree as farFolderTree,
    // faConveyorBeltAlt as fadConveyorBeltAlt,
} from '@fortawesome/pro-regular-svg-icons';
import {
    faEye,
    faSpinner,
    faHistory,
    faEllipsisHAlt,
    faSave as falSave,
    faCopy as faCopyL,
    faRedo as falRedo,
    faUndo as falUndo,
    faTools as falTools,
    faCheck as falCheck,
    faTimes as faTimesL,
    faImage as falImage,
    faLayerPlus as falLayerPlus,
    faExternalLink as falExternalLink,
    faPencilPaintbrush as falPencilPaintbrush,
} from '@fortawesome/pro-light-svg-icons';

import {
    faIcons,
    faGripLines,
    faFontCase as fadFontCase,
    faLink as fadLink,
    faList as fadList,
    faBars as fadBars,
    faCode as fadCode,
    faBlog as fadBlog,
    faBullseyePointer,
    faClock as fadClock,
    faImage as fadImage,
    faWindow as fadWindow,
    faSearch as fadSearch,
    faHeading as fadHeading,
    faTasksAlt as fadTasksAlt,
    faUserFriends as FaSocial,
    faShareAlt as fadShareAlt,
    faMailBulk as fadMailBulk,
    faThLarge as fdThLarge,
    faFilter as fadFilter,
    faGripHorizontal as fadGripHorizontal,
    faWindowRestore as faTabs,
    faAlignLeft as fadAlignLeft,
    faStopwatch as fadStopwatch,
    faVideoPlus as fadVideoPlus,
    faTypewriter as fadTypeWriter,
    faConveyorBelt as fadConveyorBelt,
    faConveyorBeltAlt as fadConveyorBeltAlt,
    faDollarSign as fadDollarSign,
    faArrowsAltV as fadArrowsAltV,
    faLaptopCode as fadLaptopCode,
    faArrowAltUp as fadArrowAltUp,
    faPhotoVideo as fadImageGallery,
    faPollPeople as fadPollPeople,
    faTabletAlt as fadTableAlt,
    faAngleDoubleLeft as fadAngleDoubleLeft,
    faEnvelopeOpenText as fadEnvelopeOpenText,
    faAngleDoubleRight as fadAngleDoubleRight,
} from '@fortawesome/pro-duotone-svg-icons';

export default function loadIcons() {
    library.add(
        // Duetone
        faTabs,
        fadBars,
        fadLink,
        fadBlog,
        fadList,
        faIcons,
        fadCode,
        fadImage,
        fadClock,
        FaSocial,
        fadSearch,
        fadWindow,
        fadTasksAlt,
        fadHeading,
        fadShareAlt,
        faGripLines,
        fadMailBulk,
        fdThLarge,
        fadFilter,
        fadStopwatch,
        fadAlignLeft,
        fadVideoPlus,
        fadFontCase,
        fadLaptopCode,
        fadArrowAltUp,
        fadTypeWriter,
        fadPollPeople,
        fadTableAlt,
        fadArrowsAltV,
        fadImageGallery,
        fadDollarSign,
        fadConveyorBelt,
        fadGripHorizontal,
        faBullseyePointer,
        fadAngleDoubleLeft,
        fadAngleDoubleRight,
        fadEnvelopeOpenText,
        fadConveyorBeltAlt,

        // Light
        falSave,
        falRedo,
        falUndo,
        falCheck,
        falImage,
        faHistory,
        faSyncAlt,
        falLayerPlus,
        falExternalLink,

        // Solid
        faBan,
        fasHome,
        fasGift,
        faTimes,
        fasDoNotEnter,
        fasCheckCircle,
        fasTimesCircle,
        fasExclamationCircle,

        // Regular
        faTable,
        farCogs,
        farFile,
        farHome,
        farGlobe,
        faSyncAlt,
        farChevronUp,
        farUserSlash,
        farChevronDown,
        farColumns,
        farFolderTree,

        faEye,
        faCog,
        faHdd,
        faEdit,
        faPlug,
        faPlus,
        faLink,
        faCogR,
        faSave,
        faEyeR,
        faCogs,
        faBars,
        faClock,
        faClone,
        faTools,
        faTrash,
        faBooks,
        faCopyL,
        faCheck,
        faVideo,
        faMagic,
        falTools,
        faMinus,
        faTimes,
        faEraser,
        faAdjust,
        faImage,
        faUnlink,
        faTimesL,
        faUpload,
        faLockAlt,
        faSpinner,
        farSearch,
        faSignOut,
        faDesktop,
        faColumns,
        faFillDrip,
        faTrashAlt,
        faEnvelope,
        faSpinnerR,
        faEllipsisV,
        faEllipsisH,
        faTabletAlt,
        faExchange,
        faAlignLeft,
        faLayerPlus,
        faAlignRight,
        faAlignCenter,
        farUserShield,
        faAlignJustify,
        faTrashAltR,
        faMobileAlt,
        faBorderAll,
        faArrowsAlt,
        faPlusCircle,
        faEllipsisVR,
        faChevronUp,
        faFileExport,
        faFileImport,
        faUserCircle,
        faInfoCircle,
        faPaintBrush,
        faLayerGroup,
        faPaperPlane,
        faLaptopCode,
        faDesktopAlt,
        faEyeDropper,
        faAngleLeft,
        faSparkles,
        faUserHeadset,
        faEllipsisHAlt,
        faGripVertical,
        faChevronDown,
        faChevronRight,
        faClipboardList,
        faLongArrowLeft,
        faChevronRightR,
        faLongArrowRight,
        faPencilPaintbrush,
        falPencilPaintbrush
    );
}
